### ISSUE TITLE
Responsividade 

### ISSUE THREAD

**Issue by yubathom** [geoinfo-smdu/tutorial-GeoSampa#1]
**Descrição do problema**
Layout poderia ser responsivo

**Possível solução**
 - Incluir `<meta name="viewport" content="width=device-width, initial-scale=1">` no head do `tutorial.html`
 - Alterar `tutorial.css` incluindo breakpoints e media queries

**Print**
Print em tamanho real de devtools com device frame para iphone 6/7/8 (375px de largura)

![Sem-Título-2](https://user-images.githubusercontent.com/4117768/75458896-5a4c4580-595d-11ea-8d5f-9ca51334b2da.png)

**Comment by stees** [comment]
Ficou obsoleto com a nova versão usando Bootstrap
