### ISSUE TITLE
Adicionar ficha técnica

### ISSUE THREAD

**Issue by stees** [geoinfo-smdu/tutorial-GeoSampa#10]
Importante relatar todos os que participaram do trabalho. Vale seguir o padrão dos Informes Urbanos e talvez diferenciar os papeis de coordenação do trabalho e de confecção do site por ordem de grau de participação.

**Comment by biamilla** [comment]
Ficha técnica adicionada ao fim da página principal. Verificar se mais algum nome deveria estar lá.
