### ISSUE TITLE
Mapa animado com moldura mudando de tamanho

### ISSUE THREAD

**Issue by stees** [geoinfo-smdu/tutorial-GeoSampa#13]
1. Logo abaixo da página inicial, a captura de tela animada muda de altura, fazendo com que o conteúdo da página fique subindo e descendo, é necessário definir a altura
2. Além disso, as duas imagens da sucessão aparecem cortadas na largura.

![image](https://user-images.githubusercontent.com/57099996/171699466-f97e1f01-3dc6-4aec-8636-4e0b4e623b74.png)

**Comment by biamilla** [comment]
O carrossel com essas duas imagens foi removido. Temos que verificar se realmente há necessidade de manter uma ou mais imagens nessa posição.
