### ISSUE TITLE
Links abrem abaixo dos títulos

### ISSUE THREAD

**Issue by biamilla** [geoinfo-smdu/tutorial-GeoSampa#8]
Quando clica nos botões da barra lateral ou do dropdown, abre abaixo dos títulos de cada "tema", direto no conteúdo da parte selecionada.

**Comment by stees** [comment]
Sugestão do @renan580: atribuir um row pra cada setor que se inicia com heading e nesse row colocar uma margem superior maior do que a altura da barra preta.
